version: 2
jobs:
  build:
    working_directory: /home/circleci/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dev requirements
          command: 'pipenv run pip install -r requirements-dev.txt'
      - run:
          name: Install pyproj itself
          command: 'pipenv run pip install -e .'
      - run:
          name: Run tests to ensure pyproj works correctly
          command: 'pipenv run nose2'
      - run:
          name: Build wheel
          command: 'pipenv run python setup.py bdist_wheel'
      - store_artifacts:
          path: dist
